# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://bharaniabhishek123.github.io/topology_docs/"

git_url = "https://github.com/bharaniabhishek123/topology_docs/tree/master/"

def custom_doc_links(name): return None
